type: rails
build:
  app:
    port: 9292
  containers:
  - image: mysql:5.6
    name: db

#  before_build:
#    command: |
#      cp config/database.raysci.yml config/database.yml

benchmark:
  target_paths:
  - /
